"""empty message

Revision ID: af7c7545858d
Revises: 12752c8da75f
Create Date: 2026-03-28 14:37:41.289634

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'af7c7545858d'
down_revision = '12752c8da75f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('databases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('max_connections', sa.Integer(), nullable=True),
    sa.Column('connection_count', sa.Integer(), nullable=True),
    sa.Column('size', sa.String(length=32), nullable=True),
    sa.Column('pg_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('databases')
    # ### end Alembic commands ###
