"""empty message

Revision ID: eddb1886d7fd
Revises: af7c7545858d
Create Date: 2026-03-29 09:46:30.075680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eddb1886d7fd'
down_revision = 'af7c7545858d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('databases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('host', sa.String(length=253), nullable=False))
        batch_op.add_column(sa.Column('port', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('db_user', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('password', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('databases', schema=None) as batch_op:
        batch_op.drop_column('password')
        batch_op.drop_column('db_user')
        batch_op.drop_column('port')
        batch_op.drop_column('host')

    # ### end Alembic commands ###
