FROM ghcr.io/astral-sh/uv:python3.14-alpine

WORKDIR /app

# Copy dependency file first for better layer caching
COPY requirements.txt .
RUN uv pip install -r requirements.txt --system

# Copy the rest of the source
COPY . .

# RUN uv run flask db upgrade

EXPOSE 5000
CMD uv run flask db upgrade &&\
    uv run flask create-test-data &&\
    uv run flask run --host 0.0.0.0 --port 5000
